### ISSUE TITLE
NameError: name 'ImageDataBunch' is not defined

### ISSUE THREAD

**Issue by Alegzandra** [mnpinto/audiotagging2019#3]
Hi! I tried to install with conda like in the instructions, but I got this error: class ImageDataBunch(ImageDataBunch):
NameError: name 'ImageDataBunch' is not defined

Doing a little research I did a fresh install with torch==1.0.0 torchvision==0.2.1 and fastai from wheel.
I still get the same error...

Could you please tell me exactly what versions you have installed? Or maybe this error is from other causes?..
Thanks a bunch!

**Comment by mnpinto** [comment]
Hi! Sorry for the late reply, I forgot to activate the notifications. Maybe you solved the problem already. I believe it's the fastai version you are using. It updated recently to version 2 and it's not backward compatible. The 'ImageDataBunch' only exists in version 1.
